/**
 * VeloxCine™ Universal Streaming, Subtitle & Aspect Suite
 * Enhanced Content Script Engine (StratumForge Labs™)
 */
(function () {
  'use strict';

  // Strictly run only in the top-level browsing context (ignore tracking/ad iframes)
  if (window !== window.top) return;

  if (window.__veloxcine_injected) return;
  window.__veloxcine_injected = true;

  console.log('%c[VeloxCine™]%c Universal Controller Active (StratumForge Labs™)', 'background:#00e5ff;color:#000;font-weight:bold;padding:2px 6px;border-radius:4px;', 'color:#00e5ff;font-weight:bold;');

  const state = {
    activeVideo: null,
    detectedPlatform: 'generic', // 'netflix' | 'prime' | 'hotstar' | 'appletv' | 'youtube' | 'generic'
    viewingPlatform: 'all',      // active tab filter in HUD
    isPremium: false,
    hudVisible: false,
    theme: 'cyan',

    aspect: {
      enabled: false,
      mode: 'original',
      customZoom: 100,
      panY: 0
    },
    subtitles: {
      enabled: true,
      isCustomDrag: false,
      fontSize: 24,
      fontColor: '#ffffff',
      brightness: 100,
      bgOpacity: 0,
      outline: true,
      posX: 50,
      posY: 88,
      fontFamily: 'Plus Jakarta Sans',
      preset: 'bottom-center',
      syncOffset: 0
    },
    video: {
      sharpen: false,
      contrast: 100,
      brightness: 100,
      audioBoost: 100
    },
    adWarp: {
      enabled: true,
      autoMute: true,
      instantSkip: true,
      isAdActive: false,
      savedVolume: 1,
      savedSpeed: 1
    },
    binge: {
      autoSkipIntro: true,
      autoSkipRecap: true,
      autoNextEpisode: false
    },
    youtube: {
      autoTheater: false,
      hideShorts: false,
      preferredRes: 'auto'
    },

    externalCues: []
  };

  // Detect Platform
  const host = window.location.hostname;
  if (host.includes('netflix.com')) state.detectedPlatform = 'netflix';
  else if (host.includes('primevideo.com') || host.includes('amazon.')) state.detectedPlatform = 'prime';
  else if (host.includes('hotstar.com')) state.detectedPlatform = 'hotstar';
  else if (host.includes('apple.com')) state.detectedPlatform = 'appletv';
  else if (host.includes('youtube.com')) state.detectedPlatform = 'youtube';

  state.viewingPlatform = state.detectedPlatform !== 'generic' ? state.detectedPlatform : 'all';

  let audioCtx = null;
  let audioSourceNode = null;
  let audioGainNode = null;
  let audioCompressorNode = null;

  /* ==========================================================================
     1. HIGH-PERFORMANCE VIDEO DETECTION & THROTTLED OBSERVER
     ========================================================================== */
  function findPrimaryVideo() {
    const videos = Array.from(document.querySelectorAll('video'));
    if (!videos.length) return null;

    // Prioritize actively playing video stream (not paused, actively progressing)
    const playingVideo = videos.find(v => !v.paused && v.currentTime > 0 && !v.ended);
    if (playingVideo) return playingVideo;

    // Fast path: reuse currently bound video if still connected and valid
    if (state.activeVideo && document.contains(state.activeVideo)) {
      return state.activeVideo;
    }

    // Platform-specific fast selectors
    if (state.detectedPlatform === 'youtube') {
      const ytVid = document.querySelector('video.html5-main-video') || document.querySelector('ytd-player video') || document.querySelector('video');
      if (ytVid) return ytVid;
    }

    // Pick largest playing or visible video
    let best = videos[0];
    let maxDimension = 0;
    for (let i = 0; i < videos.length; i++) {
      const v = videos[i];
      const dim = (v.videoWidth || v.clientWidth || 0) * (v.videoHeight || v.clientHeight || 0);
      if (dim > maxDimension) {
        maxDimension = dim;
        best = v;
      }
    }
    return best;
  }

  function bindVideo(video) {
    if (!video || state.activeVideo === video) return;
    state.activeVideo = video;
    console.log('[VeloxCine] Bound to primary video successfully.');

    applyAspectTransform();
    applyVideoEnhancements();
    // NOTE: Web Audio setupAudioContext is deferred to avoid interfering with YouTube's MSE audio pipeline

    video.addEventListener('timeupdate', onVideoTimeUpdate, { passive: true });

    if (state.detectedPlatform === 'youtube') {
      applyYouTubeSpecials();
    }
  }

  // Throttled MutationObserver: Runs only on node additions/removals, NEVER on attribute thrashing
  let mutationDebounceTimer = null;
  const observer = new MutationObserver((mutations) => {
    // Filter out mutations generated by VeloxCine's own HUD or toasts to prevent feedback loops
    let hasExternalChanges = false;
    for (let i = 0; i < mutations.length; i++) {
      const target = mutations[i].target;
      if (target && !target.closest?.('#veloxcine-hud-root') && !target.closest?.('.velox-toast')) {
        hasExternalChanges = true;
        break;
      }
    }
    if (!hasExternalChanges) return;

    if (mutationDebounceTimer) return;
    mutationDebounceTimer = setTimeout(() => {
      mutationDebounceTimer = null;
      if (!state.activeVideo || !document.contains(state.activeVideo)) {
        const v = findPrimaryVideo();
        if (v) bindVideo(v);
      }
    }, 600); // 600ms debounce
  });

  // Observe body childList only (Zero attribute watching)
  function startObserver() {
    if (document.body) {
      observer.observe(document.body, { childList: true, subtree: true });
    } else {
      document.addEventListener('DOMContentLoaded', () => {
        observer.observe(document.body, { childList: true, subtree: true });
      });
    }
  }
  startObserver();

  // YouTube SPA navigation listener
  window.addEventListener('yt-navigate-finish', () => {
    state.adWarp.isAdActive = false;
    setTimeout(() => {
      const v = findPrimaryVideo();
      if (v) {
        bindVideo(v);
        if (v.playbackRate > 2.0) v.playbackRate = 1.0;
      }
    }, 300);
  });

  /* ==========================================================================
     2. 16x HYPER-WARP AD-SKIPPER & BINGE MODE OBSERVER
     ========================================================================== */

  // Injects main-world bridge to call YouTube player.skipAd() directly
  function injectYouTubeMainWorldBridge() {
    if (document.getElementById('veloxcine-yt-bridge')) return;
    const script = document.createElement('script');
    script.id = 'veloxcine-yt-bridge';
    script.textContent = `
      (function() {
        function triggerSkip() {
          try {
            const p = document.getElementById('movie_player') || document.querySelector('.html5-video-player');
            if (p) {
              if (typeof p.skipAd === 'function') {
                p.skipAd();
              }
              if (typeof p.cancelPlayback === 'function' && (p.classList.contains('ad-showing') || p.classList.contains('ad-interrupting'))) {
                p.cancelPlayback();
              }
            }
          } catch(e) {}
        }
        window.addEventListener('veloxcine-skip-ad', triggerSkip);

        // Active safety loop in page world to ensure instant skip when button renders
        setInterval(() => {
          const p = document.getElementById('movie_player') || document.querySelector('.html5-video-player');
          if (p && (p.classList.contains('ad-showing') || p.classList.contains('ad-interrupting'))) {
            const hasSkipBtn = document.querySelector('.ytp-skip-ad-button, .ytp-ad-skip-button-modern, .ytp-ad-skip-button, button[id^="skip-button"]');
            if (hasSkipBtn && typeof p.skipAd === 'function') {
              p.skipAd();
            }
          }
        }, 200);
      })();
    `;
    (document.head || document.documentElement).appendChild(script);
  }

  // Realistic pointer + mouse event sequence to satisfy YouTube Closure event listeners
  function simulateFullClick(el) {
    if (!el) return;
    try {
      const rect = el.getBoundingClientRect();
      const clientX = rect.left + (rect.width ? rect.width / 2 : 0);
      const clientY = rect.top + (rect.height ? rect.height / 2 : 0);
      const eventInit = {
        bubbles: true,
        cancelable: true,
        view: window,
        composed: true,
        clientX: clientX || 10,
        clientY: clientY || 10,
        buttons: 1
      };

      el.dispatchEvent(new PointerEvent('pointerdown', eventInit));
      el.dispatchEvent(new MouseEvent('mousedown', eventInit));
      el.dispatchEvent(new PointerEvent('pointerup', eventInit));
      el.dispatchEvent(new MouseEvent('mouseup', eventInit));
      el.dispatchEvent(new MouseEvent('click', eventInit));
      if (typeof el.click === 'function') {
        el.click();
      }
    } catch (e) {}
  }

  let lastAdEndTime = 0;

  function detectAdAndBingeState() {
    const video = state.activeVideo || findPrimaryVideo();
    if (!video || document.hidden) return;

    // A. Binge Mode: Skip Intro & Skip Recap
    if (state.binge.autoSkipIntro || state.binge.autoSkipRecap) {
      const introButtons = [
        '[data-uia="player-skip-intro"]',
        '[data-uia="player-skip-recap"]',
        '.watch-video--skip-content-button',
        '.skip-element',
        '.atvwebplayersdk-skipelement-button',
        '.shaka-ad-skip',
        'button.skip-intro'
      ];
      for (let i = 0; i < introButtons.length; i++) {
        const btn = document.querySelector(introButtons[i]);
        if (btn && (btn.offsetParent !== null || btn.offsetWidth > 0) && !btn._veloxClicked) {
          btn._veloxClicked = true;
          setTimeout(() => { if (btn) btn._veloxClicked = false; }, 3000);
          try {
            simulateFullClick(btn);
            showToast('⚡ Binge Mode: Intro/Recap Skipped');
          } catch (e) {}
          break;
        }
      }
    }

    // B. Auto Next Episode
    if (state.binge.autoNextEpisode) {
      const nextBtn = document.querySelector('[data-uia="next-episode-seamless-button"], .atvwebplayersdk-next-episode-button');
      if (nextBtn && (nextBtn.offsetParent !== null || nextBtn.offsetWidth > 0)) {
        try {
          simulateFullClick(nextBtn);
          showToast('⚡ Binge Mode: Next Episode Started');
        } catch (e) {}
      }
    }

    // C. Bulletproof Ad Detection Across Platforms
    if (!state.adWarp.enabled) return;

    function isPrimeAdActive() {
      // 1. Prime Video SDK specific ad countdown elements
      const primeAdTimerSelectors = [
        '.atvwebplayersdk-adtimeindicator-text',
        '[class*="adtimeindicator"]',
        '[data-testid="ad-timer"]',
        '[data-testid="ad-indicator"]',
        '[data-testid="ad-badge"]',
        '.atvwebplayersdk-ad-timer',
        '.atvwebplayersdk-ad-time-indicator'
      ];

      for (let i = 0; i < primeAdTimerSelectors.length; i++) {
        const el = document.querySelector(primeAdTimerSelectors[i]);
        if (el && (el.offsetParent !== null || el.offsetWidth > 0 || el.offsetHeight > 0)) {
          const text = (el.innerText || el.textContent || '').trim();
          if (text.length > 0) return true;
        }
      }

      // 2. Scan overlay container specifically for ad countdown text (e.g. 'Ad 1 of 2', 'Ad • 0:15', 'resumes in')
      const overlay = document.querySelector('.atvwebplayersdk-overlays-container, .rendererContainer');
      if (overlay) {
        const adBadges = overlay.querySelectorAll('[class*="ad" i], [aria-label*="ad" i]');
        for (let i = 0; i < adBadges.length; i++) {
          const txt = (adBadges[i].innerText || adBadges[i].textContent || '').trim();
          if (/ad\s+\d+\s+of\s+\d+/i.test(txt) ||
              /ad\s*•\s*\d+/i.test(txt) ||
              /ad\s*:\s*\d+/i.test(txt) ||
              /resumes\s+in\s+\d+/i.test(txt)) {
            return true;
          }
        }
      }
      return false;
    }

    let isAd = false;
    if (state.detectedPlatform === 'youtube') {
      const moviePlayer = document.getElementById('movie_player') || document.querySelector('.html5-video-player');
      isAd = Boolean(
        moviePlayer && (moviePlayer.classList.contains('ad-showing') || moviePlayer.classList.contains('ad-interrupting'))
      );
    } else if (state.detectedPlatform === 'netflix') {
      isAd = Boolean(document.querySelector('.ad-container, [data-uia="ad-breakpoint"]'));
    } else if (state.detectedPlatform === 'prime') {
      isAd = isPrimeAdActive();
    } else if (state.detectedPlatform === 'hotstar') {
      isAd = Boolean(document.querySelector('.ad-timer, .ad-overlay'));
    } else {
      isAd = Boolean(document.querySelector('.ad-showing, .video-ads, [data-ad-active="true"]'));
    }

    // Skip Button Handler Across Platforms
    function clickAnySkipButton() {
      const skipSelectors = [
        // Prime Video
        '.atvwebplayersdk-skipelement-button',
        'button.atvwebplayersdk-skipelement-button',
        '.atvwebplayersdk-ad-skip-button',
        '[data-testid="ad-skip-button"]',
        '[class*="skipElement"]',
        // YouTube
        'button.ytp-ad-skip-button-modern',
        '.ytp-ad-skip-button-modern',
        'button.ytp-ad-skip-button',
        '.ytp-ad-skip-button',
        '.ytp-ad-skip-button-slot button',
        '.ytp-ad-skip-button-container button',
        'button[id^="skip-button"]',
        'button.ytp-skip-ad-button',
        '.ytp-skip-ad-button button',
        // General
        'button[class*="skip-ad"]',
        'button[class*="skip-button"]',
        'button.skip-ad',
        '.videoAdUiSkipButton',
        '.fuzzyCenter .skip-element',
        '.ytp-ad-skip-button-slot',
        '.ytp-ad-skip-button-container',
        '.ytp-skip-ad-button'
      ];

      for (let i = 0; i < skipSelectors.length; i++) {
        const btns = document.querySelectorAll(skipSelectors[i]);
        for (let j = 0; j < btns.length; j++) {
          const b = btns[j];
          if (b && (b.offsetParent !== null || b.offsetWidth > 0)) {
            simulateFullClick(b);
            if (typeof b.click === 'function') {
              try { b.click(); } catch(e) {}
            }
            const child = b.querySelector('button, [class*="skip"], .ytp-ad-text');
            if (child) {
              simulateFullClick(child);
              if (typeof child.click === 'function') {
                try { child.click(); } catch(e) {}
              }
            }
          }
        }
      }

      // Text search for skip buttons in player containers
      const allBtns = document.querySelectorAll('.html5-video-player button, .video-ads button, .ytp-ad-module button, .atvwebplayersdk-overlays-container button, .webPlayerUIContainer button');
      for (let i = 0; i < allBtns.length; i++) {
        const b = allBtns[i];
        if (b && (b.offsetParent !== null || b.offsetWidth > 0)) {
          const txt = (b.innerText || b.textContent || '').trim().toLowerCase();
          if (txt.includes('skip')) {
            simulateFullClick(b);
            if (typeof b.click === 'function') {
              try { b.click(); } catch(e) {}
            }
          }
        }
      }
    }

    const allVideos = Array.from(document.querySelectorAll('video'));

    // When ad is active
    if (isAd) {
      clickAnySkipButton();

      const isPrem = typeof VeloxLicense !== 'undefined' ? VeloxLicense.isPremium() : state.isPremium;

      allVideos.forEach(v => {
        if (!state.adWarp.isAdActive) {
          state.adWarp.isAdActive = true;
          state.adWarp.savedSpeed = (v.playbackRate && v.playbackRate > 0) ? v.playbackRate : 1;
          state.adWarp.savedVolume = (v.volume && v.volume > 0.1) ? v.volume : 1.0;
        }

        // Auto-Mute during ad
        if (state.adWarp.autoMute) {
          if (state.detectedPlatform === 'prime') {
            // On Prime Video, volume = 0 cleanly silences the ad without causing Amazon React player to lock into muted state
            v.volume = 0;
            try {
              const protoVol = Object.getOwnPropertyDescriptor(HTMLMediaElement.prototype, 'volume')?.set;
              if (protoVol) protoVol.call(v, 0);
            } catch (e) {}
          } else {
            // YouTube / Generic platforms
            if (!v.muted) {
              v.muted = true;
              try {
                const protoMuted = Object.getOwnPropertyDescriptor(HTMLMediaElement.prototype, 'muted')?.set;
                if (protoMuted) protoMuted.call(v, true);
              } catch (e) {}
              try { v.dispatchEvent(new Event('volumechange', { bubbles: true })); } catch (e) {}
            }
          }
        }

        // In Lifetime Premium: 16x Hyper-Warp
        if (isPrem) {
          try {
            v.playbackRate = 16.0;
          } catch (e) {
            try { v.playbackRate = 8.0; } catch (err) {}
          }
          // Direct prototype setter bypasses custom player overrides
          try {
            const protoSetter = Object.getOwnPropertyDescriptor(HTMLMediaElement.prototype, 'playbackRate')?.set;
            if (protoSetter) protoSetter.call(v, 16.0);
          } catch (e) {}
        }
      });

      // Dispatch skip signal to MAIN-world YouTube player bridge if on YouTube
      if (state.detectedPlatform === 'youtube') {
        window.dispatchEvent(new CustomEvent('veloxcine-skip-ad'));
      }

    } else {
      // Ad is NOT active.
      if (state.adWarp.isAdActive) {
        state.adWarp.isAdActive = false;
        lastAdEndTime = Date.now();
        showToast('✨ Playback Restored (1.0x)');
      }

      // During active post-ad transition window (5s) or if video is fast-forwarding
      const inPostAdWindow = (Date.now() - lastAdEndTime < 5000);
      const isFast = allVideos.some(v => v.playbackRate > 2.0);

      if (inPostAdWindow || isFast) {
        const restoreVol = (state.adWarp.savedVolume && state.adWarp.savedVolume > 0.1) ? state.adWarp.savedVolume : 1.0;

        allVideos.forEach(v => {
          if (v.playbackRate > 2.0 || inPostAdWindow) {
            v.playbackRate = 1.0;
            try {
              const protoSetter = Object.getOwnPropertyDescriptor(HTMLMediaElement.prototype, 'playbackRate')?.set;
              if (protoSetter) protoSetter.call(v, 1.0);
            } catch (e) {}
          }

          // Unmute video stream
          if (v.muted) {
            v.muted = false;
            try {
              const protoMuted = Object.getOwnPropertyDescriptor(HTMLMediaElement.prototype, 'muted')?.set;
              if (protoMuted) protoMuted.call(v, false);
            } catch (e) {}
            try { v.dispatchEvent(new Event('volumechange', { bubbles: true })); } catch (e) {}
          }

          // Restore volume level
          if (v.volume < 0.1 || (v.volume !== restoreVol && inPostAdWindow)) {
            v.volume = restoreVol;
            try {
              const protoVol = Object.getOwnPropertyDescriptor(HTMLMediaElement.prototype, 'volume')?.set;
              if (protoVol) protoVol.call(v, restoreVol);
            } catch (e) {}
            try { v.dispatchEvent(new Event('volumechange', { bubbles: true })); } catch (e) {}
          }
        });

        // Platform-specific UI unmute recovery for Prime Video
        if (state.detectedPlatform === 'prime') {
          const isStillMuted = allVideos.some(v => v.muted || v.volume < 0.05);
          if (isStillMuted) {
            allVideos.forEach(v => {
              v.muted = false;
              v.volume = restoreVol;
              try {
                const protoM = Object.getOwnPropertyDescriptor(HTMLMediaElement.prototype, 'muted')?.set;
                if (protoM) protoM.call(v, false);
                const protoV = Object.getOwnPropertyDescriptor(HTMLMediaElement.prototype, 'volume')?.set;
                if (protoV) protoV.call(v, restoreVol);
              } catch (e) {}
            });

            if (!window._veloxPrimeUnmuteCooldown || Date.now() - window._veloxPrimeUnmuteCooldown > 1200) {
              window._veloxPrimeUnmuteCooldown = Date.now();

              // 1. Target Prime Video volume/mute button
              const volButtons = document.querySelectorAll(`
                button.atvwebplayersdk-volumebar-mute-button,
                .atvwebplayersdk-volumebar-container button,
                [data-testid="volume-mute-button"],
                [data-testid="volume-button"],
                button[class*="volumebar" i],
                button[aria-label*="unmute" i],
                button[aria-label*="mute" i]
              `);

              for (let i = 0; i < volButtons.length; i++) {
                const btn = volButtons[i];
                if (btn && (btn.offsetParent !== null || btn.offsetWidth > 0)) {
                  try {
                    simulateFullClick(btn);
                    if (typeof btn.click === 'function') btn.click();
                    break;
                  } catch (e) {}
                }
              }

              // 2. Dispatch keyboard 'm' shortcut to Prime Video player container and window
              try {
                const keyM = new KeyboardEvent('keydown', {
                  key: 'm',
                  code: 'KeyM',
                  keyCode: 77,
                  which: 77,
                  bubbles: true,
                  cancelable: true
                });
                const target = document.querySelector('.atvwebplayersdk-bottompanel-container, .atvwebplayersdk-overlays-container, video') || document.body || window;
                target.dispatchEvent(keyM);
              } catch (e) {}
            }
          }
        }
      }
    }
  }

  // High-performance ad scanner running every 100ms
  setInterval(detectAdAndBingeState, 100);

  /* ==========================================================================
     3. ASPECT RATIO & BLACK BAR ELIMINATOR
     ========================================================================== */
  function applyAspectTransform() {
    const video = state.activeVideo || findPrimaryVideo();
    if (!video) return;
    if (!state.activeVideo) state.activeVideo = video;

    // If Aspect Ratio Override is NOT enabled, reset to natural original
    if (!state.aspect.enabled || state.aspect.mode === 'original') {
      if (state.detectedPlatform === 'prime') {
        video.style.removeProperty('transform');
        video.style.removeProperty('object-fit');
        video.style.removeProperty('width');
        video.style.removeProperty('height');
        video.style.removeProperty('top');
        video.style.removeProperty('left');
        video.style.removeProperty('transition');
      } else {
        video.style.transform = '';
        video.style.objectFit = '';
        video.style.transition = '';
      }
      return;
    }

    video.style.transition = 'transform 0.25s cubic-bezier(0.16, 1, 0.3, 1), object-fit 0.25s ease';

    const mode = state.aspect.mode;
    if (state.detectedPlatform === 'prime') {
      const surf = video.closest('.atvwebplayersdk-video-surface') || video.parentElement;
      if (surf) surf.style.setProperty('overflow', 'hidden', 'important');

      if (mode === 'stretch') {
        video.style.setProperty('top', '0px', 'important');
        video.style.setProperty('left', '0px', 'important');
        video.style.setProperty('width', '100%', 'important');
        video.style.setProperty('height', '100%', 'important');
        video.style.setProperty('object-fit', 'fill', 'important');
        video.style.setProperty('transform', 'none', 'important');
      } else if (mode === 'ultrawide') {
        video.style.setProperty('object-fit', 'cover', 'important');
        video.style.setProperty('transform', 'scale(1.334)', 'important');
      } else if (mode === 'crop169') {
        video.style.setProperty('object-fit', 'cover', 'important');
        video.style.setProperty('transform', 'scale(1.18)', 'important');
      } else if (mode === 'custom') {
        const scale = state.aspect.customZoom / 100;
        const panY = state.aspect.panY || 0;
        video.style.setProperty('object-fit', 'cover', 'important');
        video.style.setProperty('transform', `scale(${scale}) translateY(${panY}%)`, 'important');
      }
    } else {
      // YouTube and other platforms: EXACT original untouched code from accepted version
      if (mode === 'ultrawide') {
        video.style.objectFit = 'cover';
        video.style.transform = 'scale(1.334)';
      } else if (mode === 'crop169') {
        video.style.objectFit = 'cover';
        video.style.transform = 'scale(1.18)';
      } else if (mode === 'stretch') {
        video.style.objectFit = 'fill';
        video.style.transform = 'none';
      } else if (mode === 'custom') {
        const scale = state.aspect.customZoom / 100;
        const panY = state.aspect.panY || 0;
        video.style.objectFit = 'cover';
        video.style.transform = `scale(${scale}) translateY(${panY}%)`;
      }
    }
  }

  function cycleAspectRatio() {
    const modes = ['original', 'ultrawide', 'crop169', 'stretch'];
    const currentIdx = modes.indexOf(state.aspect.mode);
    const nextMode = modes[(currentIdx + 1) % modes.length];

    if ((nextMode === 'ultrawide' || nextMode === 'stretch') && !VeloxLicense.isPremium()) {
      showToast('🔒 21:9 Ultrawide is a Lifetime Premium feature');
      state.aspect.mode = 'original';
    } else {
      state.aspect.mode = nextMode;
    }

    applyAspectTransform();
    updateHUDControls();
    showToast(`Aspect: ${state.aspect.mode.toUpperCase()}`);
  }

    /* ==========================================================================
     4. SUBTITLE ENGINE (CONDITIONAL MODIFIER & OLED DIMMER)
     ========================================================================== */
  let subtitleStyleTag = null;

  function ensureYouTubeCCActive() {
    if (state.detectedPlatform !== 'youtube') return;
    try {
      const ccBtn = document.querySelector('.ytp-subtitles-button');
      if (ccBtn && ccBtn.getAttribute('aria-pressed') === 'false') {
        ccBtn.click();
      }
    } catch (e) {}
  }

  function injectSubtitleStyles() {
    if (!subtitleStyleTag) {
      subtitleStyleTag = document.createElement('style');
      subtitleStyleTag.id = 'veloxcine-dynamic-subtitles';
      (document.head || document.documentElement).appendChild(subtitleStyleTag);
    }

    const { brightness, posX, posY, enabled, preset, isCustomDrag, fontColor } = state.subtitles;
    const b = (typeof brightness === 'number' && !isNaN(brightness)) ? brightness : 100;

    let css = '';

    // 1. Subtitle Dimmer (OLED / Eye-Saver): targets text segments across YouTube, Prime Video, Shaka
    if (b < 100) {
      const opacityVal = (b / 100).toFixed(2);
      const filterVal = `brightness(${b}%)`;
      css += `
        .ytp-caption-segment,
        .atvwebplayersdk-captions-text,
        span.atvwebplayersdk-captions-text,
        span[class*="captions-text"],
        .atvwebplayersdk-subtitle-text,
        .shaka-text-container span {
          opacity: ${opacityVal} !important;
          filter: ${filterVal} !important;
          transition: opacity 0.2s ease, filter 0.2s ease !important;
        }
      `;
    }

    // 2. Subtitle Font Color Override
    if (fontColor) {
      css += `
        .ytp-caption-segment,
        .atvwebplayersdk-captions-text,
        span.atvwebplayersdk-captions-text,
        span[class*="captions-text"],
        .atvwebplayersdk-subtitle-text,
        .shaka-text-container span {
          color: ${fontColor} !important;
        }
      `;
    }

    // 3. Prime Video Overlay Base Structure: Keep wrappers full-screen & pass pointer-events to video
    css += `
      .atvwebplayersdk-captions-overlay,
      .atvwebplayersdk-captions-overlay > div,
      div[class*="captions-overlay"],
      div[class*="captions-overlay"] > div {
        position: absolute !important;
        top: 0 !important;
        left: 0 !important;
        width: 100% !important;
        height: 100% !important;
        pointer-events: none !important;
        margin: 0 !important;
        padding: 0 !important;
        transform: none !important;
      }
      .atvwebplayersdk-captions-text,
      span.atvwebplayersdk-captions-text,
      span[class*="captions-text"],
      .ytp-caption-segment {
        pointer-events: auto !important;
        cursor: grab !important;
        user-select: none !important;
        display: inline !important;
        white-space: pre-wrap !important;
        line-height: 1.4 !important;
        text-align: center !important;
      }
      .atvwebplayersdk-captions-text:active,
      span.atvwebplayersdk-captions-text:active,
      span[class*="captions-text"]:active,
      .ytp-caption-segment:active {
        cursor: grabbing !important;
      }
    `;

    // 4. Subtitle Position & Natural Dimensions (Fixes squishing and cursor tracking)
    if (enabled) {
      if (isCustomDrag && typeof posX === 'number' && typeof posY === 'number') {
        // Dragged manually with cursor: exact percentage coordinates without jump
        css += `
          /* YouTube Dragged */
          .caption-window,
          .caption-window.ytp-caption-window-bottom,
          .caption-window.ytp-caption-window-rollup {
            position: absolute !important;
            left: ${posX}% !important;
            top: ${posY}% !important;
            bottom: auto !important;
            right: auto !important;
            transform: none !important;
            margin: 0 !important;
            width: auto !important;
            max-width: 90% !important;
            text-align: center !important;
            z-index: 9999 !important;
            cursor: grab !important;
            pointer-events: auto !important;
          }
          /* Prime Video Dragged: Target the inner positioned div directly, eliminate bottom: 30px conflict */
          .atvwebplayersdk-captions-overlay > div > div,
          div[class*="captions-overlay"] > div > div,
          .atvwebplayersdk-captions-overlay div:has(> p),
          div[class*="captions-overlay"] div:has(> p) {
            position: absolute !important;
            left: ${posX}% !important;
            top: ${posY}% !important;
            bottom: auto !important;
            right: auto !important;
            transform: none !important;
            margin: 0 !important;
            width: max-content !important;
            max-width: 85% !important;
            text-align: center !important;
            display: flex !important;
            flex-direction: column !important;
            align-items: center !important;
            justify-content: flex-start !important;
            height: auto !important;
            pointer-events: none !important;
          }
          .atvwebplayersdk-captions-overlay p,
          div[class*="captions-overlay"] p {
            width: auto !important;
            max-width: 100% !important;
            text-align: center !important;
            margin: 0 !important;
            pointer-events: none !important;
          }
        `;
      } else {
        // Presets: Bottom Center, Top Center, Bottom Black Bar, Top Black Bar
        let ytPos = '';
        let primeVertical = '';

        if (preset === 'top-center') {
          ytPos = `left: 50% !important; top: 8% !important; bottom: auto !important; transform: translateX(-50%) !important;`;
          primeVertical = `top: 8% !important; bottom: auto !important; justify-content: flex-start !important;`;
        } else if (preset === 'top-black-bar') {
          ytPos = `left: 50% !important; top: 2% !important; bottom: auto !important; transform: translateX(-50%) !important;`;
          primeVertical = `top: 2% !important; bottom: auto !important; justify-content: flex-start !important;`;
        } else if (preset === 'bottom-black-bar') {
          ytPos = `left: 50% !important; bottom: 2% !important; top: auto !important; transform: translateX(-50%) !important;`;
          primeVertical = `bottom: 2% !important; top: auto !important; justify-content: flex-end !important;`;
        } else {
          // 'bottom-center' (Default Position): Centered horizontally, anchored at bottom above controls
          ytPos = `left: 50% !important; bottom: 8% !important; top: auto !important; transform: translateX(-50%) !important;`;
          primeVertical = `bottom: 8% !important; top: auto !important; justify-content: flex-end !important;`;
        }

        css += `
          /* YouTube Preset */
          .caption-window,
          .caption-window.ytp-caption-window-bottom,
          .caption-window.ytp-caption-window-rollup {
            position: absolute !important;
            ${ytPos}
            right: auto !important;
            margin: 0 !important;
            width: auto !important;
            max-width: 90% !important;
            text-align: center !important;
            z-index: 9999 !important;
            cursor: grab !important;
            pointer-events: auto !important;
          }
          /* Prime Video Preset: Full width inner line container centered horizontally */
          .atvwebplayersdk-captions-overlay > div > div,
          div[class*="captions-overlay"] > div > div,
          .atvwebplayersdk-captions-overlay div:has(> p),
          div[class*="captions-overlay"] div:has(> p) {
            position: absolute !important;
            width: 100% !important;
            left: 0 !important;
            right: 0 !important;
            ${primeVertical}
            margin: 0 !important;
            text-align: center !important;
            display: flex !important;
            flex-direction: column !important;
            align-items: center !important;
            transform: none !important;
            height: auto !important;
            pointer-events: none !important;
          }
          .atvwebplayersdk-captions-overlay p,
          div[class*="captions-overlay"] p {
            width: 100% !important;
            text-align: center !important;
            margin: 0 !important;
            padding: 0 40px !important;
            box-sizing: border-box !important;
            pointer-events: none !important;
          }
        `;
      }
    }

    subtitleStyleTag.textContent = css;
  }

  function toggleDimmer() {
    if (!VeloxLicense.isPremium()) {
      showToast('🔒 Subtitle Dimmer is a Lifetime Premium feature');
      return;
    }
    state.subtitles.brightness = state.subtitles.brightness === 100 ? 50 : 100;
    injectSubtitleStyles();
    showToast(`Subtitle Dimmer: ${state.subtitles.brightness}%`);
  }

  /* ==========================================================================
     5. YOUTUBE SPECIALS (Auto Theater, Hide Shorts, Preferred Res)
     ========================================================================== */
  function applyYouTubeSpecials() {
    if (state.detectedPlatform !== 'youtube') return;

    // Auto Theater Mode
    if (state.youtube.autoTheater) {
      const theaterBtn = document.querySelector('.ytp-size-button');
      const isTheater = document.querySelector('ytd-watch-flexy[theater]');
      if (theaterBtn && !isTheater) {
        theaterBtn.click();
      }
    }

    // Hide Shorts Row
    let shortsStyle = document.getElementById('veloxcine-yt-shorts');
    if (state.youtube.hideShorts) {
      if (!shortsStyle) {
        shortsStyle = document.createElement('style');
        shortsStyle.id = 'veloxcine-yt-shorts';
        document.head.appendChild(shortsStyle);
      }
      shortsStyle.textContent = `
        ytd-rich-shelf-renderer[is-shorts],
        ytd-reel-shelf-renderer,
        ytd-guide-entry-renderer a[title="Shorts"] {
          display: none !important;
        }
      `;
    } else if (shortsStyle) {
      shortsStyle.remove();
    }
  }

  /* ==========================================================================
     6. EXTERNAL SUBTITLE PARSER
     ========================================================================== */
  function parseSrtOrVtt(text) {
    const cues = [];
    const lines = text.replace(/\r\n/g, '\n').replace(/\r/g, '\n').split('\n');
    let i = 0;

    function timeToSeconds(tStr) {
      if (!tStr) return 0;
      const parts = tStr.trim().replace(',', '.').split(':');
      if (parts.length === 3) {
        return parseFloat(parts[0]) * 3600 + parseFloat(parts[1]) * 60 + parseFloat(parts[2]);
      } else if (parts.length === 2) {
        return parseFloat(parts[0]) * 60 + parseFloat(parts[1]);
      }
      return 0;
    }

    while (i < lines.length) {
      const line = lines[i].trim();
      if (!line || line.startsWith('WEBVTT') || line.startsWith('NOTE')) {
        i++;
        continue;
      }
      let timeLine = line;
      if (!timeLine.includes('-->') && i + 1 < lines.length && lines[i + 1].includes('-->')) {
        i++;
        timeLine = lines[i];
      }
      if (timeLine.includes('-->')) {
        const [startStr, endStr] = timeLine.split('-->');
        const start = timeToSeconds(startStr);
        const end = timeToSeconds(endStr.trim().split(' ')[0]);
        i++;
        const textLines = [];
        while (i < lines.length && lines[i].trim() !== '') {
          textLines.push(lines[i]);
          i++;
        }
        cues.push({ start, end, text: textLines.join('\n') });
      }
      i++;
    }
    return cues;
  }

  function loadExternalSubtitles(file) {
    if (!VeloxLicense.isPremium()) {
      showToast('🔒 External Subtitle Loader is a Lifetime Premium feature');
      return;
    }
    const reader = new FileReader();
    reader.onload = (e) => {
      const cues = parseSrtOrVtt(e.target.result);
      if (cues.length) {
        state.externalCues = cues;
        showToast(`Loaded ${cues.length} Cues from ${file.name}`);
        const textElem = document.querySelector('.velox-custom-sub-text');
        if (textElem) textElem.textContent = 'Subtitles Loaded & Synced';
      }
    };
    reader.readAsText(file);
  }

  function onVideoTimeUpdate() {
    if (!state.externalCues.length || !state.activeVideo) return;
    const current = state.activeVideo.currentTime + (state.subtitles.syncOffset || 0);
    const match = state.externalCues.find(c => current >= c.start && current <= c.end);
    const subElem = document.querySelector('.velox-custom-sub-text');
    if (!subElem) return;

    if (match) {
      subElem.textContent = match.text;
      subElem.style.display = 'inline-block';
    } else {
      subElem.textContent = '';
      subElem.style.display = 'none';
    }
  }

  /* ==========================================================================
     7. VIDEO ENHANCEMENTS & AUDIO GAIN
     ========================================================================== */
  function applyVideoEnhancements() {
    const video = state.activeVideo;
    if (!video) return;

    let filterStr = '';
    if (state.video.sharpen) {
      if (VeloxLicense.isPremium()) {
        filterStr += 'contrast(106%) saturate(108%) ';
      } else {
        state.video.sharpen = false;
      }
    }
    if (state.video.brightness !== 100) filterStr += `brightness(${state.video.brightness}%) `;
    if (state.video.contrast !== 100) filterStr += `contrast(${state.video.contrast}%) `;
    video.style.filter = filterStr.trim() || 'none';
  }

  function setupAudioContext(video) {
    if (audioCtx) return;
    try {
      const AudioContext = window.AudioContext || window.webkitAudioContext;
      if (!AudioContext) return;
      audioCtx = new AudioContext();
      audioSourceNode = audioCtx.createMediaElementSource(video);
      audioGainNode = audioCtx.createGain();

      // Studio-grade dynamic range compressor & brickwall soft limiter
      // Eliminates digital clipping, harsh distortion, and graininess at high gain levels
      audioCompressorNode = audioCtx.createDynamicsCompressor();
      audioCompressorNode.threshold.setValueAtTime(-14, audioCtx.currentTime); // dB
      audioCompressorNode.knee.setValueAtTime(30, audioCtx.currentTime);      // soft knee for transparent compression
      audioCompressorNode.ratio.setValueAtTime(12, audioCtx.currentTime);     // limiter ratio
      audioCompressorNode.attack.setValueAtTime(0.003, audioCtx.currentTime); // 3ms fast attack catches transients
      audioCompressorNode.release.setValueAtTime(0.25, audioCtx.currentTime); // 250ms smooth musical decay

      // Signal Chain: Video Source -> Gain Booster -> Studio Limiter/Compressor -> Audio Destination
      audioSourceNode.connect(audioGainNode);
      audioGainNode.connect(audioCompressorNode);
      audioCompressorNode.connect(audioCtx.destination);
    } catch (e) {
      console.warn('[VeloxCine] Web Audio setup:', e);
    }
  }

  function setAudioGain(percent) {
    if (percent > 100 && !audioCtx && state.activeVideo) {
      setupAudioContext(state.activeVideo);
    }
    if (audioCtx && audioCtx.state === 'suspended') {
      audioCtx.resume().catch(() => {});
    }
    if (!audioGainNode) return;
    const isPrem = typeof VeloxLicense !== 'undefined' ? VeloxLicense.isPremium() : state.isPremium;
    if (percent > 100 && !isPrem) {
      showToast('🔒 600% Audio Booster requires Lifetime Premium');
      return;
    }
    const targetGain = percent / 100;
    if (audioGainNode.gain.setValueAtTime && audioCtx) {
      audioGainNode.gain.setValueAtTime(targetGain, audioCtx.currentTime);
    } else {
      audioGainNode.gain.value = targetGain;
    }
  }

  /* ==========================================================================
     8. NON-INTRUSIVE OVERLAY & TOAST (IN-PAGE HUD CONTROLS REMOVED)
     ========================================================================== */
  function createHUD() {
    // Clean up any legacy in-page HUD elements
    const oldPill = document.getElementById('velox-trigger-pill');
    if (oldPill) oldPill.remove();
    const oldNudge = document.getElementById('velox-nudge-pill');
    if (oldNudge) oldNudge.remove();
    const oldPanel = document.getElementById('velox-main-panel');
    if (oldPanel) oldPanel.remove();
    const oldAnchor = document.getElementById('veloxcine-subtitle-anchor');
    if (oldAnchor) oldAnchor.remove();

    if (document.getElementById('veloxcine-hud-root')) return;

    const root = document.createElement('div');
    root.id = 'veloxcine-hud-root';
    root.innerHTML = `
      <!-- Lightweight Notification Toast for Shortcuts / State -->
      <div class="velox-toast" id="velox-toast">
        <span id="velox-toast-msg">VeloxCine Active</span>
      </div>
    `;

    (document.body || document.documentElement).appendChild(root);
  }

  function setupHUDInteractions() {
    // In-page HUD controls removed per user request. Settings are accessed via the extension icon.
  }

  function setupDraggableAnchor() {
    let isDragging = false;
    let grabOffsetX = 0;
    let grabOffsetY = 0;

    function onDragStart(e) {
      // ONLY trigger dragging if clicking the actual subtitle text itself
      const textTarget = e.target.closest(`
        .caption-window,
        .ytp-caption-segment,
        .atvwebplayersdk-captions-text,
        span.atvwebplayersdk-captions-text,
        .atvwebplayersdk-subtitle-text,
        .shaka-text-container span
      `);
      if (!textTarget) return;

      const boxRect = textTarget.getBoundingClientRect();
      grabOffsetX = e.clientX - boxRect.left;
      grabOffsetY = e.clientY - boxRect.top;

      state.subtitles.enabled = true;
      state.subtitles.isCustomDrag = true;
      state.subtitles.preset = 'custom';
      isDragging = true;
      e.preventDefault();
      e.stopPropagation();
    }

    function onDragMove(e) {
      if (!isDragging) return;
      const player = (state.activeVideo ? state.activeVideo.parentElement : null) ||
                     document.querySelector('.atvwebplayersdk-overlays-container, .rendererContainer, .webPlayerUIContainer') ||
                     document.getElementById('movie_player') ||
                     document.querySelector('.html5-video-player') ||
                     document.body;
      const playerRect = player.getBoundingClientRect();
      const width = playerRect.width > 0 ? playerRect.width : window.innerWidth;
      const height = playerRect.height > 0 ? playerRect.height : window.innerHeight;

      // Exact top-left position minus grab offset so the box doesn't jump
      const leftPx = e.clientX - playerRect.left - grabOffsetX;
      const topPx = e.clientY - playerRect.top - grabOffsetY;

      const pctX = Math.max(1, Math.min(85, (leftPx / width) * 100));
      const pctY = Math.max(1, Math.min(92, (topPx / height) * 100));

      state.subtitles.posX = Math.round(pctX * 10) / 10;
      state.subtitles.posY = Math.round(pctY * 10) / 10;
      injectSubtitleStyles();
    }

    function onDragEnd() {
      if (isDragging) {
        isDragging = false;
        showToast(`Subtitle Position Saved (${state.subtitles.posX}%, ${state.subtitles.posY}%)`);
        chrome.storage.local.get('veloxcine_settings').then(data => {
          const s = data.veloxcine_settings || { global: {}, profiles: {} };
          s.global = s.global || {};
          s.global.subEnabled = true;
          s.global.subPosition = 'custom';
          s.global.subCustomX = state.subtitles.posX;
          s.global.subCustomY = state.subtitles.posY;
          if (state.detectedPlatform !== 'generic') {
            s.profiles = s.profiles || {};
            s.profiles[state.detectedPlatform] = s.profiles[state.detectedPlatform] || {};
            s.profiles[state.detectedPlatform].subEnabled = true;
            s.profiles[state.detectedPlatform].subPosition = 'custom';
            s.profiles[state.detectedPlatform].subCustomX = state.subtitles.posX;
            s.profiles[state.detectedPlatform].subCustomY = state.subtitles.posY;
          }
          chrome.storage.local.set({ veloxcine_settings: s });
        }).catch(() => {});
      }
    }

    document.addEventListener('mousedown', onDragStart, true);
    window.addEventListener('mousemove', onDragMove, true);
    window.addEventListener('mouseup', onDragEnd, true);
  }

  function updateHUDControls() {
    // In-page HUD controls removed.
  }

  /* ==========================================================================
     10. KEYBOARD SHORTCUTS
     ========================================================================== */
  window.addEventListener('keydown', (e) => {
    if (['INPUT', 'TEXTAREA'].includes(document.activeElement?.tagName)) return;

    if (e.key === 'z' || e.key === 'Z') {
      cycleAspectRatio();
    } else if (e.key === 'd' || e.key === 'D') {
      toggleDimmer();
    }
  });

  function applySettingsObject(prof) {
    if (!prof) return;

    // Aspect Override
    if (prof.defaultAspect) {
      state.aspect.mode = prof.defaultAspect;
      state.aspect.enabled = prof.defaultAspect !== 'original';
    } else if (prof.aspectEnabled !== undefined) {
      state.aspect.enabled = Boolean(prof.aspectEnabled);
    }
    applyAspectTransform();

    // Subtitle Position & Modifier
    if (prof.subPosition) {
      state.subtitles.preset = prof.subPosition;
      state.subtitles.enabled = true;
      if (prof.subPosition === 'custom' && prof.subCustomX !== undefined && prof.subCustomY !== undefined) {
        state.subtitles.isCustomDrag = true;
        state.subtitles.posX = prof.subCustomX;
        state.subtitles.posY = prof.subCustomY;
      } else {
        state.subtitles.isCustomDrag = false;
        if (prof.subPosition === 'top-center') { state.subtitles.posX = 50; state.subtitles.posY = 8; }
        else if (prof.subPosition === 'bottom-center') { state.subtitles.posX = 50; state.subtitles.posY = 88; }
        else if (prof.subPosition === 'bottom-black-bar') { state.subtitles.posX = 50; state.subtitles.posY = 98; }
        else if (prof.subPosition === 'top-black-bar') { state.subtitles.posX = 50; state.subtitles.posY = 2; }
      }
      ensureYouTubeCCActive();
    } else if (prof.subEnabled !== undefined) {
      state.subtitles.enabled = Boolean(prof.subEnabled);
    }

    if (prof.brightness !== undefined) {
      state.subtitles.brightness = parseInt(prof.brightness, 10);
    }
    if (prof.subColor) {
      state.subtitles.fontColor = prof.subColor;
    }
    injectSubtitleStyles();

    if (prof.adWarpEnabled !== undefined) state.adWarp.enabled = prof.adWarpEnabled;
    if (prof.bingeEnabled !== undefined) {
      state.binge.autoSkipIntro = prof.bingeEnabled;
      state.binge.autoSkipRecap = prof.bingeEnabled;
    }
  }

  function resetAllSettingsToDefaults() {
    state.aspect.enabled = false;
    state.aspect.mode = 'original';
    const video = state.activeVideo || findPrimaryVideo();
    if (video) {
      state.activeVideo = video;
      video.style.transform = '';
      video.style.objectFit = '';
      video.style.transition = '';
      if (video.playbackRate && video.playbackRate !== 1.0) video.playbackRate = 1.0;
      if (video.muted) video.muted = false;
    }

    // Reset Subtitles directly to Canonical Bottom Center
    state.subtitles.enabled = true;
    state.subtitles.preset = 'bottom-center';
    state.subtitles.isCustomDrag = false;
    state.subtitles.posX = 50;
    state.subtitles.posY = 88;
    state.subtitles.brightness = 100;
    state.subtitles.fontColor = '#ffffff';
    injectSubtitleStyles();

    // Clear element inline overrides so CSS rules take cleanly across YouTube and Prime Video
    document.querySelectorAll(`
      .caption-window,
      .ytp-caption-window-bottom,
      .ytp-caption-window-rollup,
      .atvwebplayersdk-captions-overlay,
      .atvwebplayersdk-captions-overlay > div,
      div[class*="captions-overlay"] > div,
      .atvwebplayersdk-captions-text
    `).forEach(el => {
      el.style.left = '';
      el.style.top = '';
      el.style.bottom = '';
      el.style.right = '';
      el.style.transform = '';
      el.style.margin = '';
      el.style.opacity = '';
      el.style.filter = '';
      el.style.color = '';
    });
    window.dispatchEvent(new Event('resize'));

    state.adWarp.enabled = true;
    state.binge.autoSkipIntro = true;
    state.binge.autoSkipRecap = true;
    state.youtube.autoTheater = false;
    state.youtube.hideShorts = false;

    ensureYouTubeCCActive();
    showToast('↺ VeloxCine: Subtitles Reset to Bottom Center');
  }

  chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
    if (msg.action === 'RESET_SETTINGS') {
      resetAllSettingsToDefaults();
      sendResponse({ status: 'OK' });
    } else if (msg.action === 'APPLY_SETTINGS_NOW') {
      applySettingsObject(msg.settings);
      sendResponse({ status: 'OK' });
    } else if (msg.action === 'PING') {
      sendResponse({ status: 'OK', platform: state.detectedPlatform, videoBound: Boolean(state.activeVideo) });
    } else if (msg.action === 'CYCLE_ASPECT') {
      cycleAspectRatio();
      sendResponse({ mode: state.aspect.mode });
    } else if (msg.action === 'TOGGLE_DIMMER') {
      toggleDimmer();
      sendResponse({ brightness: state.subtitles.brightness });
    } else if (msg.action === 'TOGGLE_HUD') {
      showToast('VeloxCine: Controls are in Extension Toolbar Icon');
      sendResponse({ visible: false });
    }
    return true;
  });

  function showToast(text) {
    const toast = document.getElementById('velox-toast');
    const msg = document.getElementById('velox-toast-msg');
    if (!toast || !msg) return;
    msg.textContent = text;
    toast.classList.add('show');
    clearTimeout(toast._timer);
    toast._timer = setTimeout(() => {
      toast.classList.remove('show');
    }, 2800);
  }

  // Persistent Settings Loader
  async function loadPersistedSettings() {
    try {
      const data = await chrome.storage.local.get('veloxcine_settings');
      const settings = data.veloxcine_settings || {};
      const platform = state.detectedPlatform;
      // Merge global settings with platform-specific profile
      const prof = { ...(settings.global || {}), ...(platform !== 'generic' && settings.profiles?.[platform] ? settings.profiles[platform] : {}) };
      applySettingsObject(prof);
    } catch (e) {}
  }

  try {
    chrome.storage.onChanged.addListener((changes, area) => {
      if (area === 'local' && changes.veloxcine_settings) {
        loadPersistedSettings();
      }
    });
  } catch (e) {}

  async function init() {
    if (typeof VeloxLicense !== 'undefined' && VeloxLicense.init) {
      try {
        await VeloxLicense.init();
        state.isPremium = VeloxLicense.isPremium();
      } catch(e) {}
    }
    await loadPersistedSettings();
    injectYouTubeMainWorldBridge();
    createHUD();
    injectSubtitleStyles();
    setupDraggableAnchor();
    const v = findPrimaryVideo();
    if (v) bindVideo(v);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
