/**
 * VeloxCine™ Universal Streaming, Subtitle & Aspect Suite
 * Enhanced Content Script Engine (StratumForge Labs™)
 */
(function () {
  'use strict';

  if (window.__veloxcine_injected) return;
  window.__veloxcine_injected = true;

  console.log('%c[VeloxCine™]%c Universal Controller Active (StratumForge Labs™)', 'background:#00e5ff;color:#000;font-weight:bold;padding:2px 6px;border-radius:4px;', 'color:#00e5ff;font-weight:bold;');

  const state = {
    activeVideo: null,
    detectedPlatform: 'generic', // 'netflix' | 'prime' | 'hotstar' | 'appletv' | 'youtube' | 'generic'
    viewingPlatform: 'all',      // active tab filter in HUD
    isPremium: false,
    hudVisible: false,
    theme: 'cyan',

    aspect: {
      mode: 'original',
      customZoom: 100,
      panY: 0
    },
    subtitles: {
      fontSize: 24,
      fontColor: '#ffffff',
      brightness: 100,
      bgOpacity: 0,
      outline: true,
      posX: 50,
      posY: 88,
      fontFamily: 'Plus Jakarta Sans',
      preset: 'bottom-center',
      syncOffset: 0
    },
    video: {
      sharpen: false,
      contrast: 100,
      brightness: 100,
      audioBoost: 100
    },
    adWarp: {
      enabled: true,
      autoMute: true,
      instantSkip: true,
      isAdActive: false,
      savedVolume: 1,
      savedSpeed: 1
    },
    binge: {
      autoSkipIntro: true,
      autoSkipRecap: true,
      autoNextEpisode: false
    },
    youtube: {
      autoTheater: false,
      hideShorts: false,
      preferredRes: 'auto'
    },

    externalCues: []
  };

  // Detect Platform
  const host = window.location.hostname;
  if (host.includes('netflix.com')) state.detectedPlatform = 'netflix';
  else if (host.includes('primevideo.com') || host.includes('amazon.')) state.detectedPlatform = 'prime';
  else if (host.includes('hotstar.com')) state.detectedPlatform = 'hotstar';
  else if (host.includes('apple.com')) state.detectedPlatform = 'appletv';
  else if (host.includes('youtube.com')) state.detectedPlatform = 'youtube';

  state.viewingPlatform = state.detectedPlatform !== 'generic' ? state.detectedPlatform : 'all';

  let audioCtx = null;
  let audioSourceNode = null;
  let audioGainNode = null;
  let audioCompressorNode = null;

  /* ==========================================================================
     1. HIGH-PERFORMANCE VIDEO DETECTION & THROTTLED OBSERVER
     ========================================================================== */
  function findPrimaryVideo() {
    // Fast path: reuse currently bound video if still connected and valid
    if (state.activeVideo && document.contains(state.activeVideo)) {
      return state.activeVideo;
    }

    // Platform-specific fast selectors (Zero layout reflow)
    if (state.detectedPlatform === 'youtube') {
      const ytVid = document.querySelector('video.html5-main-video') || document.querySelector('ytd-player video') || document.querySelector('video');
      if (ytVid) return ytVid;
    }

    const videos = document.querySelectorAll('video');
    if (!videos.length) return null;

    // Pick largest playing or visible video without getBoundingClientRect()
    let best = videos[0];
    let maxDimension = 0;
    for (let i = 0; i < videos.length; i++) {
      const v = videos[i];
      const dim = (v.videoWidth || v.clientWidth || 0) * (v.videoHeight || v.clientHeight || 0);
      if (dim > maxDimension) {
        maxDimension = dim;
        best = v;
      }
    }
    return best;
  }

  function bindVideo(video) {
    if (!video || state.activeVideo === video) return;
    state.activeVideo = video;
    console.log('[VeloxCine] Bound to primary video successfully.');

    applyAspectTransform();
    applyVideoEnhancements();
    // NOTE: Web Audio setupAudioContext is deferred to avoid interfering with YouTube's MSE audio pipeline

    video.addEventListener('timeupdate', onVideoTimeUpdate, { passive: true });

    if (state.detectedPlatform === 'youtube') {
      applyYouTubeSpecials();
    }
  }

  // Throttled MutationObserver: Runs only on node additions/removals, NEVER on attribute thrashing
  let mutationDebounceTimer = null;
  const observer = new MutationObserver((mutations) => {
    // Filter out mutations generated by VeloxCine's own HUD or toasts to prevent feedback loops
    let hasExternalChanges = false;
    for (let i = 0; i < mutations.length; i++) {
      const target = mutations[i].target;
      if (target && !target.closest?.('#veloxcine-hud-root') && !target.closest?.('.velox-toast')) {
        hasExternalChanges = true;
        break;
      }
    }
    if (!hasExternalChanges) return;

    if (mutationDebounceTimer) return;
    mutationDebounceTimer = setTimeout(() => {
      mutationDebounceTimer = null;
      if (!state.activeVideo || !document.contains(state.activeVideo)) {
        const v = findPrimaryVideo();
        if (v) bindVideo(v);
      }
    }, 600); // 600ms debounce
  });

  // Observe body childList only (Zero attribute watching)
  function startObserver() {
    if (document.body) {
      observer.observe(document.body, { childList: true, subtree: true });
    } else {
      document.addEventListener('DOMContentLoaded', () => {
        observer.observe(document.body, { childList: true, subtree: true });
      });
    }
  }
  startObserver();

  // YouTube SPA navigation listener
  window.addEventListener('yt-navigate-finish', () => {
    state.adWarp.isAdActive = false;
    setTimeout(() => {
      const v = findPrimaryVideo();
      if (v) {
        bindVideo(v);
        if (v.playbackRate > 2.0) v.playbackRate = 1.0;
      }
    }, 300);
  });

  /* ==========================================================================
     2. 16x HYPER-WARP AD-SKIPPER & BINGE MODE OBSERVER
     ========================================================================== */

  // Injects main-world bridge to call YouTube player.skipAd() directly
  function injectYouTubeMainWorldBridge() {
    if (document.getElementById('veloxcine-yt-bridge')) return;
    const script = document.createElement('script');
    script.id = 'veloxcine-yt-bridge';
    script.textContent = `
      (function() {
        function triggerSkip() {
          try {
            const p = document.getElementById('movie_player') || document.querySelector('.html5-video-player');
            if (p) {
              if (typeof p.skipAd === 'function') {
                p.skipAd();
              }
              if (typeof p.cancelPlayback === 'function' && (p.classList.contains('ad-showing') || p.classList.contains('ad-interrupting'))) {
                p.cancelPlayback();
              }
            }
          } catch(e) {}
        }
        window.addEventListener('veloxcine-skip-ad', triggerSkip);

        // Active safety loop in page world to ensure instant skip when button renders
        setInterval(() => {
          const p = document.getElementById('movie_player') || document.querySelector('.html5-video-player');
          if (p && (p.classList.contains('ad-showing') || p.classList.contains('ad-interrupting'))) {
            const hasSkipBtn = document.querySelector('.ytp-skip-ad-button, .ytp-ad-skip-button-modern, .ytp-ad-skip-button, button[id^="skip-button"]');
            if (hasSkipBtn && typeof p.skipAd === 'function') {
              p.skipAd();
            }
          }
        }, 200);
      })();
    `;
    (document.head || document.documentElement).appendChild(script);
  }

  // Realistic pointer + mouse event sequence to satisfy YouTube Closure event listeners
  function simulateFullClick(el) {
    if (!el) return;
    try {
      const rect = el.getBoundingClientRect();
      const clientX = rect.left + (rect.width ? rect.width / 2 : 0);
      const clientY = rect.top + (rect.height ? rect.height / 2 : 0);
      const eventInit = {
        bubbles: true,
        cancelable: true,
        view: window,
        composed: true,
        clientX: clientX || 10,
        clientY: clientY || 10,
        buttons: 1
      };

      el.dispatchEvent(new PointerEvent('pointerdown', eventInit));
      el.dispatchEvent(new MouseEvent('mousedown', eventInit));
      el.dispatchEvent(new PointerEvent('pointerup', eventInit));
      el.dispatchEvent(new MouseEvent('mouseup', eventInit));
      el.dispatchEvent(new MouseEvent('click', eventInit));
      if (typeof el.click === 'function') {
        el.click();
      }

      // Also trigger on parent container in case listener is on wrapper
      if (el.parentElement && el.parentElement !== document.body) {
        el.parentElement.dispatchEvent(new PointerEvent('pointerdown', eventInit));
        el.parentElement.dispatchEvent(new MouseEvent('click', eventInit));
        if (typeof el.parentElement.click === 'function') el.parentElement.click();
      }
    } catch (e) {}
  }

  function detectAdAndBingeState() {
    const video = state.activeVideo || findPrimaryVideo();
    if (!video || document.hidden) return;

    // A. Binge Mode: Skip Intro & Skip Recap
    if (state.binge.autoSkipIntro || state.binge.autoSkipRecap) {
      const introButtons = [
        '[data-uia="player-skip-intro"]',
        '[data-uia="player-skip-recap"]',
        '.watch-video--skip-content-button',
        '.skip-element',
        '.atvwebplayersdk-skipelement-button',
        '.shaka-ad-skip',
        'button.skip-intro'
      ];
      for (let i = 0; i < introButtons.length; i++) {
        const btn = document.querySelector(introButtons[i]);
        if (btn && (btn.offsetParent !== null || btn.offsetWidth > 0)) {
          try {
            simulateFullClick(btn);
            showToast('⚡ Binge Mode: Intro/Recap Skipped');
          } catch (e) {}
          break;
        }
      }
    }

    // B. Auto Next Episode
    if (state.binge.autoNextEpisode) {
      const nextBtn = document.querySelector('[data-uia="next-episode-seamless-button"], .atvwebplayersdk-next-episode-button');
      if (nextBtn && (nextBtn.offsetParent !== null || nextBtn.offsetWidth > 0)) {
        try {
          simulateFullClick(nextBtn);
          showToast('⚡ Binge Mode: Next Episode Started');
        } catch (e) {}
      }
    }

    // C. Bulletproof Ad Detection Across Platforms
    if (!state.adWarp.enabled) return;

    let isAd = false;
    if (state.detectedPlatform === 'youtube') {
      const moviePlayer = document.getElementById('movie_player') || document.querySelector('.html5-video-player');
      isAd = Boolean(
        (moviePlayer && (moviePlayer.classList.contains('ad-showing') || moviePlayer.classList.contains('ad-interrupting'))) ||
        document.querySelector('.ad-showing, .ad-interrupting, .ytp-ad-player-overlay:not([style*="display: none"])')
      );
    } else if (state.detectedPlatform === 'netflix') {
      isAd = Boolean(document.querySelector('.ad-container, [data-uia="ad-breakpoint"]'));
    } else if (state.detectedPlatform === 'prime') {
      isAd = Boolean(document.querySelector('.ad-showing, .adMarker, .fuzzyCenter .ad-overlay'));
    } else if (state.detectedPlatform === 'hotstar') {
      isAd = Boolean(document.querySelector('.ad-timer, .ad-overlay'));
    } else {
      isAd = Boolean(document.querySelector('.ad-showing, .video-ads, [data-ad-active="true"]'));
    }

    // Click ALL YouTube & Platform Skip Ad Buttons Instantly (Active for both Free & Premium)
    const skipSelectors = [
      '.ytp-skip-ad-button',
      '.ytp-ad-skip-button-modern',
      '.ytp-ad-skip-button',
      '.ytp-ad-skip-button-container button',
      '.ytp-ad-skip-button-slot button',
      '.ytp-ad-skip-button-container',
      '.ytp-ad-skip-button-slot',
      'button.ytp-ad-skip-button-modern',
      'button.ytp-ad-skip-button',
      'button.ytp-skip-ad-button',
      'button[id^="skip-button"]',
      'button[class*="skip-ad"]',
      'button[class*="skip-button"]',
      'button.skip-ad',
      '.videoAdUiSkipButton',
      '.fuzzyCenter .skip-element'
    ];

    let clickedSkip = false;
    for (let i = 0; i < skipSelectors.length; i++) {
      const btns = document.querySelectorAll(skipSelectors[i]);
      for (let j = 0; j < btns.length; j++) {
        const b = btns[j];
        if (b && (b.offsetParent !== null || b.offsetWidth > 0 || b.offsetHeight > 0)) {
          try {
            simulateFullClick(b);
            window.dispatchEvent(new CustomEvent('veloxcine-skip-ad'));
            clickedSkip = true;
            showToast('⚡ VeloxCine: Ad Skipped');
          } catch (e) {}
          break;
        }
      }
      if (clickedSkip) break;
    }

    // Additional text search for modern YouTube pill buttons ("Skip >|")
    if (!clickedSkip && (isAd || state.detectedPlatform === 'youtube')) {
      const candidateButtons = document.querySelectorAll('.html5-video-player button, .ytp-ad-module button, .ytp-ad-skip-button-slot *');
      for (let i = 0; i < candidateButtons.length; i++) {
        const b = candidateButtons[i];
        const txt = (b.innerText || b.textContent || '').trim().toLowerCase();
        if (txt.includes('skip') && (b.offsetParent !== null || b.offsetWidth > 0)) {
          try {
            simulateFullClick(b);
            window.dispatchEvent(new CustomEvent('veloxcine-skip-ad'));
            clickedSkip = true;
            showToast('⚡ VeloxCine: Ad Skipped');
          } catch (e) {}
          break;
        }
      }
    }

    // When ad is active
    if (isAd) {
      if (!state.adWarp.isAdActive) {
        state.adWarp.isAdActive = true;
        state.adWarp.savedSpeed = video.playbackRate || 1;
        state.adWarp.savedVolume = video.volume;
      }

      // Auto-Mute during ad
      if (state.adWarp.autoMute && !video.muted) {
        video.muted = true;
      }

      const isPrem = typeof VeloxLicense !== 'undefined' ? VeloxLicense.isPremium() : state.isPremium;

      // In Lifetime Premium: 16x Hyper-Warp + Fast Forward
      if (isPrem) {
        try {
          video.playbackRate = 16.0;
        } catch (e) {
          video.playbackRate = 8.0;
        }

        // Instant Skip Jump: Fast-forward straight to near the end of the ad segment
        if (isFinite(video.duration) && video.duration > 0 && video.currentTime < video.duration - 0.2) {
          video.currentTime = video.duration - 0.1;
        }
      }

      // Dispatch skip signal to main-world player
      window.dispatchEvent(new CustomEvent('veloxcine-skip-ad'));

      // If ad has reached the end or is stuck on the post-ad screen, auto-advance
      if (isFinite(video.duration) && video.duration > 0 && video.currentTime >= video.duration - 0.25) {
        window.dispatchEvent(new CustomEvent('veloxcine-skip-ad'));
        if (video.paused) {
          try { video.play(); } catch(e) {}
        }
      }

    } else {
      // Ad is NOT active. Ensure speed is 1.0x and audio is unmuted (never stuck at 16x)
      if (state.adWarp.isAdActive || (video.playbackRate && video.playbackRate > 2.0)) {
        state.adWarp.isAdActive = false;
        video.playbackRate = 1.0;
        if (state.adWarp.autoMute && video.muted) {
          video.muted = false;
          if (state.adWarp.savedVolume !== undefined) video.volume = state.adWarp.savedVolume;
        }
        showToast('✨ Playback Restored (1.0x)');
      }
    }
  }

  // High-performance ad scanner running every 200ms
  setInterval(detectAdAndBingeState, 200);

  /* ==========================================================================
     3. ASPECT RATIO & BLACK BAR ELIMINATOR
     ========================================================================== */
  function applyAspectTransform() {
    const video = state.activeVideo;
    if (!video) return;

    video.style.transition = 'transform 0.25s cubic-bezier(0.16, 1, 0.3, 1), object-fit 0.25s ease';

    const mode = state.aspect.mode;
    if (mode === 'original') {
      video.style.transform = 'none';
      video.style.objectFit = 'contain';
    } else if (mode === 'ultrawide') {
      video.style.objectFit = 'cover';
      video.style.transform = 'scale(1.334)';
    } else if (mode === 'crop169') {
      video.style.objectFit = 'cover';
      video.style.transform = 'scale(1.18)';
    } else if (mode === 'stretch') {
      video.style.objectFit = 'fill';
      video.style.transform = 'none';
    } else if (mode === 'custom') {
      const scale = state.aspect.customZoom / 100;
      const panY = state.aspect.panY || 0;
      video.style.objectFit = 'cover';
      video.style.transform = `scale(${scale}) translateY(${panY}%)`;
    }
  }

  function cycleAspectRatio() {
    const modes = ['original', 'ultrawide', 'crop169', 'stretch'];
    const currentIdx = modes.indexOf(state.aspect.mode);
    const nextMode = modes[(currentIdx + 1) % modes.length];

    if ((nextMode === 'ultrawide' || nextMode === 'stretch') && !VeloxLicense.isPremium()) {
      showToast('🔒 21:9 Ultrawide is a Lifetime Premium feature');
      state.aspect.mode = 'original';
    } else {
      state.aspect.mode = nextMode;
    }

    applyAspectTransform();
    updateHUDControls();
    showToast(`Aspect: ${state.aspect.mode.toUpperCase()}`);
  }

  /* ==========================================================================
     4. SUBTITLE ENGINE & DRAG-AND-DROP ANCHOR
     ========================================================================== */
  let subtitleStyleTag = null;

  function forceNativeCaptionPosition() {
    const { posX, posY } = state.subtitles;
    const containers = document.querySelectorAll(
      '#ytp-caption-window-container, .ytp-caption-window-container, .caption-window, .player-timedtext, .atvwebplayersdk-subtitles-container'
    );
    containers.forEach(el => {
      try {
        el.style.setProperty('position', 'absolute', 'important');
        el.style.setProperty('left', `${posX}%`, 'important');
        el.style.setProperty('top', `${posY}%`, 'important');
        el.style.setProperty('bottom', 'auto', 'important');
        el.style.setProperty('right', 'auto', 'important');
        el.style.setProperty('margin', '0', 'important');
        el.style.setProperty('transform', 'translate(-50%, -50%)', 'important');
        el.style.setProperty('text-align', 'center', 'important');
      } catch (e) {}
    });
  }

  function injectSubtitleStyles() {
    if (!subtitleStyleTag) {
      subtitleStyleTag = document.createElement('style');
      subtitleStyleTag.id = 'veloxcine-dynamic-subtitles';
      (document.head || document.documentElement).appendChild(subtitleStyleTag);
    }

    const { fontSize, fontColor, brightness, bgOpacity, outline, fontFamily, posX, posY } = state.subtitles;
    const bg = bgOpacity > 0 ? `rgba(0, 0, 0, ${bgOpacity / 100})` : 'transparent';
    const textShadow = outline
      ? '0 2px 4px rgba(0,0,0,0.95), 0 0 6px rgba(0,0,0,0.9), 1px 1px 2px #000, -1px -1px 2px #000'
      : 'none';
    const filter = `brightness(${brightness}%)`;

    const textSelectors = [
      '.player-timedtext',
      '.player-timedtext-text-container',
      '.player-timedtext-text-container span',
      '.atvwebplayersdk-subtitle-text',
      '.shaka-text-container span',
      '.subtitle-display span',
      '.ytp-caption-segment',
      '.caption-visual-line',
      '.velox-custom-sub-text'
    ].join(', ');

    const containerSelectors = [
      '#ytp-caption-window-container',
      '.ytp-caption-window-container',
      '.caption-window',
      '.ytp-caption-window-bottom',
      '.ytp-caption-window-rollup',
      '.player-timedtext',
      '.player-timedtext-text-container',
      '.atvwebplayersdk-subtitles-container',
      '.atvwebplayersdk-captions-overlay',
      '.shaka-text-container'
    ].join(', ');

    subtitleStyleTag.textContent = `
      ${textSelectors} {
        font-size: ${fontSize}px !important;
        color: ${fontColor} !important;
        background-color: ${bg} !important;
        filter: ${filter} !important;
        text-shadow: ${textShadow} !important;
        font-family: ${fontFamily}, system-ui, sans-serif !important;
        transition: filter 0.15s ease, font-size 0.15s ease !important;
      }
      ${containerSelectors} {
        position: absolute !important;
        left: ${posX}% !important;
        top: ${posY}% !important;
        bottom: auto !important;
        right: auto !important;
        margin: 0 !important;
        transform: translate(-50%, -50%) !important;
        text-align: center !important;
        display: flex !important;
        justify-content: center !important;
        cursor: grab !important;
      }
      .caption-window:active,
      .ytp-caption-window-container:active,
      .player-timedtext:active {
        cursor: grabbing !important;
      }
    `;

    const anchor = document.getElementById('veloxcine-subtitle-anchor');
    if (anchor) {
      anchor.style.left = `${posX}%`;
      anchor.style.top = `${posY}%`;
      anchor.style.transform = 'translate(-50%, -50%)';
    }

    forceNativeCaptionPosition();
  }

  function toggleDimmer() {
    if (!VeloxLicense.isPremium()) {
      showToast('🔒 Subtitle Dimmer is a Lifetime Premium feature');
      return;
    }
    state.subtitles.brightness = state.subtitles.brightness === 100 ? 50 : 100;
    injectSubtitleStyles();
    showToast(`Subtitle Dimmer: ${state.subtitles.brightness}%`);
  }

  /* ==========================================================================
     5. YOUTUBE SPECIALS (Auto Theater, Hide Shorts, Preferred Res)
     ========================================================================== */
  function applyYouTubeSpecials() {
    if (state.detectedPlatform !== 'youtube') return;

    // Auto Theater Mode
    if (state.youtube.autoTheater) {
      const theaterBtn = document.querySelector('.ytp-size-button');
      const isTheater = document.querySelector('ytd-watch-flexy[theater]');
      if (theaterBtn && !isTheater) {
        theaterBtn.click();
      }
    }

    // Hide Shorts Row
    let shortsStyle = document.getElementById('veloxcine-yt-shorts');
    if (state.youtube.hideShorts) {
      if (!shortsStyle) {
        shortsStyle = document.createElement('style');
        shortsStyle.id = 'veloxcine-yt-shorts';
        document.head.appendChild(shortsStyle);
      }
      shortsStyle.textContent = `
        ytd-rich-shelf-renderer[is-shorts],
        ytd-reel-shelf-renderer,
        ytd-guide-entry-renderer a[title="Shorts"] {
          display: none !important;
        }
      `;
    } else if (shortsStyle) {
      shortsStyle.remove();
    }
  }

  /* ==========================================================================
     6. EXTERNAL SUBTITLE PARSER
     ========================================================================== */
  function parseSrtOrVtt(text) {
    const cues = [];
    const lines = text.replace(/\r\n/g, '\n').replace(/\r/g, '\n').split('\n');
    let i = 0;

    function timeToSeconds(tStr) {
      if (!tStr) return 0;
      const parts = tStr.trim().replace(',', '.').split(':');
      if (parts.length === 3) {
        return parseFloat(parts[0]) * 3600 + parseFloat(parts[1]) * 60 + parseFloat(parts[2]);
      } else if (parts.length === 2) {
        return parseFloat(parts[0]) * 60 + parseFloat(parts[1]);
      }
      return 0;
    }

    while (i < lines.length) {
      const line = lines[i].trim();
      if (!line || line.startsWith('WEBVTT') || line.startsWith('NOTE')) {
        i++;
        continue;
      }
      let timeLine = line;
      if (!timeLine.includes('-->') && i + 1 < lines.length && lines[i + 1].includes('-->')) {
        i++;
        timeLine = lines[i];
      }
      if (timeLine.includes('-->')) {
        const [startStr, endStr] = timeLine.split('-->');
        const start = timeToSeconds(startStr);
        const end = timeToSeconds(endStr.trim().split(' ')[0]);
        i++;
        const textLines = [];
        while (i < lines.length && lines[i].trim() !== '') {
          textLines.push(lines[i]);
          i++;
        }
        cues.push({ start, end, text: textLines.join('\n') });
      }
      i++;
    }
    return cues;
  }

  function loadExternalSubtitles(file) {
    if (!VeloxLicense.isPremium()) {
      showToast('🔒 External Subtitle Loader is a Lifetime Premium feature');
      return;
    }
    const reader = new FileReader();
    reader.onload = (e) => {
      const cues = parseSrtOrVtt(e.target.result);
      if (cues.length) {
        state.externalCues = cues;
        showToast(`Loaded ${cues.length} Cues from ${file.name}`);
        const textElem = document.querySelector('.velox-custom-sub-text');
        if (textElem) textElem.textContent = 'Subtitles Loaded & Synced';
      }
    };
    reader.readAsText(file);
  }

  function onVideoTimeUpdate() {
    if (!state.externalCues.length || !state.activeVideo) return;
    const current = state.activeVideo.currentTime + (state.subtitles.syncOffset || 0);
    const match = state.externalCues.find(c => current >= c.start && current <= c.end);
    const subElem = document.querySelector('.velox-custom-sub-text');
    if (!subElem) return;

    if (match) {
      subElem.textContent = match.text;
      subElem.style.display = 'inline-block';
    } else {
      subElem.textContent = '';
      subElem.style.display = 'none';
    }
  }

  /* ==========================================================================
     7. VIDEO ENHANCEMENTS & AUDIO GAIN
     ========================================================================== */
  function applyVideoEnhancements() {
    const video = state.activeVideo;
    if (!video) return;

    let filterStr = '';
    if (state.video.sharpen) {
      if (VeloxLicense.isPremium()) {
        filterStr += 'contrast(106%) saturate(108%) ';
      } else {
        state.video.sharpen = false;
      }
    }
    if (state.video.brightness !== 100) filterStr += `brightness(${state.video.brightness}%) `;
    if (state.video.contrast !== 100) filterStr += `contrast(${state.video.contrast}%) `;
    video.style.filter = filterStr.trim() || 'none';
  }

  function setupAudioContext(video) {
    if (audioCtx) return;
    try {
      const AudioContext = window.AudioContext || window.webkitAudioContext;
      if (!AudioContext) return;
      audioCtx = new AudioContext();
      audioSourceNode = audioCtx.createMediaElementSource(video);
      audioGainNode = audioCtx.createGain();

      // Studio-grade dynamic range compressor & brickwall soft limiter
      // Eliminates digital clipping, harsh distortion, and graininess at high gain levels
      audioCompressorNode = audioCtx.createDynamicsCompressor();
      audioCompressorNode.threshold.setValueAtTime(-14, audioCtx.currentTime); // dB
      audioCompressorNode.knee.setValueAtTime(30, audioCtx.currentTime);      // soft knee for transparent compression
      audioCompressorNode.ratio.setValueAtTime(12, audioCtx.currentTime);     // limiter ratio
      audioCompressorNode.attack.setValueAtTime(0.003, audioCtx.currentTime); // 3ms fast attack catches transients
      audioCompressorNode.release.setValueAtTime(0.25, audioCtx.currentTime); // 250ms smooth musical decay

      // Signal Chain: Video Source -> Gain Booster -> Studio Limiter/Compressor -> Audio Destination
      audioSourceNode.connect(audioGainNode);
      audioGainNode.connect(audioCompressorNode);
      audioCompressorNode.connect(audioCtx.destination);
    } catch (e) {
      console.warn('[VeloxCine] Web Audio setup:', e);
    }
  }

  function setAudioGain(percent) {
    if (percent > 100 && !audioCtx && state.activeVideo) {
      setupAudioContext(state.activeVideo);
    }
    if (audioCtx && audioCtx.state === 'suspended') {
      audioCtx.resume().catch(() => {});
    }
    if (!audioGainNode) return;
    const isPrem = typeof VeloxLicense !== 'undefined' ? VeloxLicense.isPremium() : state.isPremium;
    if (percent > 100 && !isPrem) {
      showToast('🔒 600% Audio Booster requires Lifetime Premium');
      return;
    }
    const targetGain = percent / 100;
    if (audioGainNode.gain.setValueAtTime && audioCtx) {
      audioGainNode.gain.setValueAtTime(targetGain, audioCtx.currentTime);
    } else {
      audioGainNode.gain.value = targetGain;
    }
  }

  /* ==========================================================================
     8. NON-INTRUSIVE OVERLAY & TOAST (IN-PAGE HUD CONTROLS REMOVED)
     ========================================================================== */
  function createHUD() {
    // Clean up any legacy in-page HUD elements
    const oldPill = document.getElementById('velox-trigger-pill');
    if (oldPill) oldPill.remove();
    const oldNudge = document.getElementById('velox-nudge-pill');
    if (oldNudge) oldNudge.remove();
    const oldPanel = document.getElementById('velox-main-panel');
    if (oldPanel) oldPanel.remove();
    const oldAnchor = document.getElementById('veloxcine-subtitle-anchor');
    if (oldAnchor) oldAnchor.remove();

    if (document.getElementById('veloxcine-hud-root')) return;

    const root = document.createElement('div');
    root.id = 'veloxcine-hud-root';
    root.innerHTML = `
      <!-- Lightweight Notification Toast for Shortcuts / State -->
      <div class="velox-toast" id="velox-toast">
        <span id="velox-toast-msg">VeloxCine Active</span>
      </div>
    `;

    (document.body || document.documentElement).appendChild(root);
  }

  function setupHUDInteractions() {
    // In-page HUD controls removed per user request. Settings are accessed via the extension icon.
  }

  function setupDraggableAnchor() {
    let isDragging = false;

    function onDragStart(e) {
      const isSubTarget = e.target.closest('.caption-window') ||
                          e.target.closest('.ytp-caption-segment') ||
                          e.target.closest('.ytp-caption-window-container') ||
                          e.target.closest('.player-timedtext');

      if (!isSubTarget) return;

      isDragging = true;
      e.preventDefault();
    }

    function onDragMove(e) {
      if (!isDragging) return;
      const player = (state.activeVideo ? state.activeVideo.parentElement : null) ||
                     document.getElementById('movie_player') ||
                     document.querySelector('.html5-video-player') ||
                     document.body;
      const rect = player.getBoundingClientRect();
      const width = rect.width > 0 ? rect.width : window.innerWidth;
      const height = rect.height > 0 ? rect.height : window.innerHeight;
      const pctX = Math.max(5, Math.min(95, ((e.clientX - rect.left) / width) * 100));
      const pctY = Math.max(5, Math.min(98, ((e.clientY - rect.top) / height) * 100));
      state.subtitles.posX = Math.round(pctX);
      state.subtitles.posY = Math.round(pctY);
      injectSubtitleStyles();
    }

    function onDragEnd() {
      if (isDragging) {
        isDragging = false;
        showToast(`Subtitle Position Saved (${state.subtitles.posX}%, ${state.subtitles.posY}%)`);
      }
    }

    document.addEventListener('mousedown', onDragStart);
    window.addEventListener('mousemove', onDragMove);
    window.addEventListener('mouseup', onDragEnd);
  }

  function updateHUDControls() {
    // In-page HUD controls removed.
  }

  /* ==========================================================================
     10. KEYBOARD SHORTCUTS
     ========================================================================== */
  window.addEventListener('keydown', (e) => {
    if (['INPUT', 'TEXTAREA'].includes(document.activeElement?.tagName)) return;

    if (e.key === 'z' || e.key === 'Z') {
      cycleAspectRatio();
    } else if (e.key === 'd' || e.key === 'D') {
      toggleDimmer();
    }
  });

  chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
    if (msg.action === 'PING') {
      sendResponse({ status: 'OK', platform: state.detectedPlatform, videoBound: Boolean(state.activeVideo) });
    } else if (msg.action === 'CYCLE_ASPECT') {
      cycleAspectRatio();
      sendResponse({ mode: state.aspect.mode });
    } else if (msg.action === 'TOGGLE_DIMMER') {
      toggleDimmer();
      sendResponse({ brightness: state.subtitles.brightness });
    } else if (msg.action === 'TOGGLE_HUD') {
      showToast('VeloxCine: Controls are in Extension Toolbar Icon');
      sendResponse({ visible: false });
    }
    return true;
  });

  function showToast(text) {
    const toast = document.getElementById('velox-toast');
    const msg = document.getElementById('velox-toast-msg');
    if (!toast || !msg) return;
    msg.textContent = text;
    toast.classList.add('show');
    clearTimeout(toast._timer);
    toast._timer = setTimeout(() => {
      toast.classList.remove('show');
    }, 2800);
  }

  // Persistent Settings Loader
  async function loadPersistedSettings() {
    try {
      const data = await chrome.storage.local.get('veloxcine_settings');
      const settings = data.veloxcine_settings || {};
      const platform = state.detectedPlatform;
      const prof = platform !== 'generic' && settings.profiles?.[platform] ? settings.profiles[platform] : (settings.global || {});

      if (prof.adWarpEnabled !== undefined) state.adWarp.enabled = prof.adWarpEnabled;
      if (prof.bingeEnabled !== undefined) {
        state.binge.autoSkipIntro = prof.bingeEnabled;
        state.binge.autoSkipRecap = prof.bingeEnabled;
      }
      if (prof.brightness !== undefined) {
        state.subtitles.brightness = prof.brightness;
        injectSubtitleStyles();
      }
      if (prof.defaultAspect) {
        state.aspect.mode = prof.defaultAspect;
        applyAspectTransform();
      }
    } catch (e) {}
  }

  try {
    chrome.storage.onChanged.addListener((changes, area) => {
      if (area === 'local' && changes.veloxcine_settings) {
        loadPersistedSettings();
      }
    });
  } catch (e) {}

  async function init() {
    if (typeof VeloxLicense !== 'undefined' && VeloxLicense.init) {
      try {
        await VeloxLicense.init();
        state.isPremium = VeloxLicense.isPremium();
      } catch(e) {}
    }
    await loadPersistedSettings();
    injectYouTubeMainWorldBridge();
    createHUD();
    injectSubtitleStyles();
    setupDraggableAnchor();
    const v = findPrimaryVideo();
    if (v) bindVideo(v);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
